name: Assign Issue to Project

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/orgs/Sylvester-Team/projects/2'
          column_name: 'To do'
          github_token: ${{ secrets.GITHUB_TOKEN }}
