name: Assign Issue to Project

on:
  workflow_dispatch:  # This line allows manual triggering of the workflow
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - develop
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/Sylvester-Team/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
